S01 us01 navbarvisitor
WildCodeSchool/orleans-php-2003-project-ambl pull request #12
Opened 2020-04-15 16:41 UTC by Grefleon

Setting up the navbar

2020-04-15 16:53 UTC, kodev-sudo submitted a review, later dismissed
Everything is ok !

2020-04-15 21:39 UTC, sblondeau requested changes

2020-04-15 21:39 UTC, sblondeau commented on src/View/_navbar.html.twig
> +        <h1>AMBL</h1>
hum, non pour moi le h1 ce n'est pas sa place dans la navbar
plutot en dessous, dans une première section, en fonction de votre wireframe

2020-04-15 21:39 UTC, sblondeau commented on public/assets/css/navbar.css
> +}
le style du h1 devrait etre dans le fichier style.css (voir ma remarque plus bas)

2020-04-16 07:25 UTC, kodev-sudo approved these changes

2020-04-16 15:43 UTC, sblondeau approved these changes

2020-04-16 15:43 UTC, merged