S05 us15 send id request
WildCodeSchool/orleans-php-2003-project-ambl pull request #136
Opened 2020-05-11 15:49 UTC by Grefleon

2020-05-11 16:42 UTC, dante18 submitted a review, later dismissed
OK

2020-05-11 17:58 UTC, sblondeau requested changes

2020-05-11 17:58 UTC, sblondeau commented on src/Controller/IdentificationController.php
> +        $uploadDir = '../public/assets/images/identifications';
non les images uploadées doivent etre dans public/uploads/blablabla
les "assets" contiennent les fichiers statiques (donc non uploadés)
ça marche si tu laisses comme ça mais ce n'est pas logique

2020-05-11 17:58 UTC, sblondeau commented on src/Controller/IdentificationController.php
> +        $uploadDir = '../public/assets/images/identifications';
et penser à modif le gitignore aussi dans ce cas

2020-05-11 18:21 UTC, dante18 approved these changes
OK

2020-05-12 06:39 UTC, sblondeau approved these changes

2020-05-12 06:39 UTC, merged