S01 us02 sectionassociation
WildCodeSchool/orleans-php-2003-project-ambl pull request #14
Opened 2020-04-16 08:58 UTC by dante18

Adding "Association" section on Homepage

2020-04-16 15:09 UTC, sblondeau requested changes

2020-04-16 15:09 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam atque delectus dolorem ducimus
pas de lorem 
le texte n'est pas administrable, donc il faut que ce soit le texte final ici (si vous ne savez pas quoi mettre, il faut demander au client de vous fournir ce texte)

2020-04-16 15:09 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                    <img clas="img-fluid" src="https://via.placeholder.com/300x300" alt="">
idem ici, pas de placeholder d'image
vous demandez au client de vous fournir des images
(mais vous en avez déjà qqunes sur le site, sinon prenez des images Libres de droit sur unsplash, pixabay, etc.)

2020-04-16 16:44 UTC, kodev-sudo submitted a review, later dismissed

2020-04-16 19:26 UTC, sblondeau requested changes

2020-04-16 19:26 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                <div class="col-xs-12 col-sm-6 col-md-7 col-xl-8">
il faut mettre col-12 (pas besoin de rajouter le xs pour ce breakpoint).
et en plus, de base le col-12 est tjs appliqué, donc pas besoin de mettre cette classe.

2020-04-16 19:26 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                        A travers différentes initiatives comme les rassemblements, randonnées pédestres, conférences et développement d’actions environnementales, l’AMBL propose à ses adhérents et a
À travers (majucule accentuée)

2020-04-16 20:10 UTC, Grefleon approved these changes
Les erreurs signalées ont bien été corrigées.

2020-04-17 08:10 UTC, sblondeau approved these changes

2020-04-17 08:10 UTC, merged