Fix catalog admin
WildCodeSchool/orleans-php-2003-project-ambl pull request #145
Opened 2020-05-12 16:26 UTC by dante18

Correction of various errors and change of the formatting of the administration part of the catalog.

2020-05-12 20:46 UTC, Grefleon submitted a review, later dismissed
Ok

2020-05-12 21:23 UTC, sblondeau requested changes
2-3 petites choses minimes à revoir
cependant, la PR de fix est beaucoup trop  grosse, énormément de fichiers/code retouché, c'est beaucoup trop long 
faites attention sur les suivantes de bien faire une PR par fix, comme pour les US, il faut bien découper les choses, sinon ça devient vite impossible à relire ;-)

2020-05-12 21:23 UTC, sblondeau commented on src/Model/CatalogManager.php
> +                    lEFT JOIN toxicity ON toxicity.id=element.toxicity_id
LEFT

2020-05-12 21:23 UTC, sblondeau commented on src/View/Catalog/index.html.twig
> +                                                <I>{{ element.latin_name }}</I>
i en minuscule

2020-05-12 21:23 UTC, sblondeau commented on src/View/CatalogAdmin/add.html.twig
> +                    <h1><h1>Ajout d'un élément au catalogue</h1></h1>
double h1

2020-05-12 21:23 UTC, sblondeau commented on public/assets/css/catalog.css
> +    background-color: white;
variable CSS pour les couleurs (à plusieurs endroits)

2020-05-13 08:22 UTC, kanarticho approved these changes
OK

2020-05-13 08:57 UTC, sblondeau approved these changes

2020-05-13 08:57 UTC, merged