ajout du footer
WildCodeSchool/orleans-php-2003-project-ambl pull request #15
Opened 2020-04-16 13:14 UTC by kanarticho

2020-04-16 16:41 UTC, kodev-sudo submitted a review, later dismissed

2020-04-16 19:23 UTC, sblondeau requested changes

2020-04-16 19:23 UTC, sblondeau commented on public/assets/css/footer.css
> +    color: #e2f3e1;
variable CSS pour toutes les couleurs

2020-04-16 19:23 UTC, sblondeau commented on public/assets/css/footer.css
> +    color: #e2f3e1;
idem partout ou y a besoin dans le fichier

2020-04-16 19:23 UTC, sblondeau commented on public/assets/css/footer.css
> +.btn-primary {
si tu surcharges la couleur des boutons, c'est pour tout le site, pas que pour le footer non ? 
donc plutot dans style.css

2020-04-16 19:23 UTC, sblondeau commented on src/View/footer.html.twig
> +    <div class="container-fluid text-center">
identation

2020-04-16 19:23 UTC, sblondeau commented on src/View/footer.html.twig
> +                <ul class="list-unstyled">
il existe la balise html address pour les adresses ;-) c'est mieux semantiquement parlant
https://developer.mozilla.org/fr/docs/Web/HTML/Element/address

2020-04-16 19:23 UTC, sblondeau commented on src/View/footer.html.twig
> +                <h5 class="text-uppercase">A propos</h5>
À propos (majuscule accentuée)

2020-04-16 19:23 UTC, sblondeau commented on src/View/footer.html.twig
> +    <div class="footer-copyright text-center py-3">© 2020 Copyright
copyright est un terme anglais, ça n'a pas de valeur juridique en droit français ;-)

2020-04-16 19:23 UTC, sblondeau commented on src/View/footer.html.twig
> +                        <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
ah... là on est dans un cas limite limite
Normalement les mentions légales, c'est une autre page donc une autre US. Là vous l'avez mis dans une modale donc pas vraiment une autre page mais ça revient un peu au même. 
Bon maintenant c'est fait, donc laissez le.

2020-04-17 10:13 UTC, sblondeau approved these changes

2020-04-17 10:13 UTC, merged