S02 us09 cataloguechampignons
WildCodeSchool/orleans-php-2003-project-ambl pull request #38
Opened 2020-04-22 08:19 UTC by dante18

Display of the catalog content for the mushroom section

2020-04-22 12:25 UTC, Grefleon submitted a review, later dismissed
Seems alright

2020-04-22 15:19 UTC, sblondeau requested changes
les images seront uploadées par l'admin, ce sont des "données" au meme titre que la BDD
donc pas versionnées sur github ;-)
enlève ces images stp, ne sont versionnées que les images statiques, pour la déco du site


ensuite, ton code est plutot propre dans l'ensemble, modélisation, utilisation du simple-mvc est bien. Mais j'ai beaucoup de retour car ta PR est beaucoup trop grosse. Je m'en suis rendu compte un fois que j'avais tout relu, mais la US est mal découpée. 
tu aurais du avoir 
- une US pour afficher les éléments (requete SELECT, LIMIT, affichage des card)
- une US pour gérer le filtre par catégorie (ajout du form, traitement du form et affichage différencié en fonction du type sélectionné). Cette seconde partie n'est pas terminée car si j'ai le form, je n'ai pas le traitement différencié, "mushroom" etant écrit en dur dans ton code.

Idéalement, retravaillez le backlog pour découper la US, enlève ici des choses pour que je n'ai que le code de la US 1. On valide.

Dans un second temps, tu fais la US part 2 en ajoutant le form et le traitement.
A ta dispo pour en parler si besoin

2020-04-22 15:19 UTC, sblondeau commented on public/assets/css/catalog.css
> +    background-color: #fff;
couleur en variable css

2020-04-22 15:19 UTC, sblondeau commented on src/Model/CatalogManager.php
> +        $query .= '.type_id = type.id WHERE type.name = "' . $type . '" LIMIT ' . self::MAX_RESULT;
je ne sais pas trop comment tu compte faire passer l'info du type, mais logiquement ça va venir d'un form, ou un bouton, via la query string. Bref, fait une requete préparée ça me semble mieux.

2020-04-22 15:19 UTC, sblondeau commented on src/View/Catalog/index.html.twig
> +                                        <form action="" method="post">
c'est un form de recherche, il ne sert pas à mettre à jour les données.
plutot en method="get"

2020-04-22 15:19 UTC, sblondeau commented on src/View/Catalog/index.html.twig
> +                <div class="toolsbox" class="row">
me semble y avoir beaucoup de div là. J'ai une section > container > row > col-12 > card > card-body > row > col-sm-6 > form :o 
faut beaucoup simplifier à mon avis
et tu peux pas avoir 2 attributs class, la bonne syntaxe serait `class="toolsbox row"`

2020-04-22 15:19 UTC, sblondeau commented on src/Controller/CatalogController.php
> +        $elements = $catalogManager->selectAllByType('mushroom');
l'info "mushroom" finalement tu la récupère de ton formulaire non ? donc serait pas à mettre "en dur" ici

2020-04-22 15:19 UTC, sblondeau commented on src/View/Catalog/index.html.twig
> +                    <div class="col-md-3">
pb d'indentation

2020-04-22 15:19 UTC, sblondeau commented on src/View/Catalog/index.html.twig
> +                    {% endfor %}
idem là, j'ai deux div sur la meme ligne, le endif et endfor sur le meme niveau, revoir indentation

2020-04-22 15:19 UTC, sblondeau commented on src/View/Catalog/index.html.twig
> +                    {% if loop.index is divisible by(4) %}
non tu te compliques beaucoup la vie. Tu n'as absolument pas besoin de faire ça (verif que c'est divisible par 4) car bootstrap va faire du flex-wrap tout seul et gérer le retour à la ligne. Tu ne dois pas recréé une div class="row" pour chaque ligne. Tu en créé une seule (le row c'est ton élément parent display:flex) et il va contenir toutes tes  lignes.
Ce qui permet de gérer le responsive plus simplement, en en affichant 4 de front sur grand écran, mais peut etre que 2 sur écran moyen, et 1 seul par ligne sur téléphone.

2020-04-22 16:08 UTC, kanarticho submitted a review, later dismissed
Ok !

2020-04-22 16:13 UTC, sblondeau requested changes
c'est bien mieux !
par contre les images sont tjs là ! à déversionner (essaie via `git rm --cached nom_image`) qui deversionne un fichier sans l'effacer vraiment.

2020-04-22 16:13 UTC, sblondeau commented on src/Model/CatalogManager.php
> +        if ($type == '') {
non, si tu veux mushroom par défaut, il faut que tu le mette en valeur par défaut de ta méthode
donc plutot 
    public function selectAllByType(string $type = 'mushroom'): array

et dans ton controller, juste un selectAllByType()  et non selectAllByType('')

2020-04-22 16:13 UTC, sblondeau commented on src/Model/CatalogManager.php
> +        $query .= '.type_id = type.id WHERE type.name = "' . $type . '" LIMIT ' . self::MAX_RESULT;
et j'insiste, il me faut une requete préparée

2020-04-22 16:59 UTC, Grefleon submitted a review, later dismissed
The query seems (not) good

2020-04-22 17:04 UTC, Grefleon approved these changes
I mean, now it seems good

2020-04-23 20:04 UTC, sblondeau approved these changes

2020-04-23 20:04 UTC, merged