S02_US06 association presentation
WildCodeSchool/orleans-php-2003-project-ambl pull request #40
Opened 2020-04-22 15:53 UTC by kanarticho

Creation of the association page (presentation part)

2020-04-22 16:09 UTC, dante18 submitted a review, later dismissed
OK !

2020-04-22 16:16 UTC, sblondeau requested changes

2020-04-22 16:16 UTC, sblondeau commented on public/assets/css/association.css
> +h1, h2{
c'est générique ça, plutot dans style.css non ?

2020-04-22 16:16 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                Nous souhaitons également développer le goût des sciences naturelles et le respect de la nature par une meilleure connaissance des végétaux.
te manque des `<br/>` pour les retours à la ligne non ?

2020-04-22 16:36 UTC, kanarticho commented
Conflicts w/ navbar resolved, addition of break lines and modif of style.css

2020-04-22 16:52 UTC, dante18 submitted a review, later dismissed
OK !

2020-04-23 14:23 UTC, AnthonyBerduck commented
Je suis pas vraiment sur de valider cette PR a ta place Sylvain ...

2020-04-23 20:05 UTC, sblondeau submitted a review, later dismissed

2020-04-24 07:14 UTC, dante18 approved these changes
OK

2020-04-24 08:14 UTC, merged