S04 us25 updateevent
WildCodeSchool/orleans-php-2003-project-ambl pull request #70
Opened 2020-05-04 14:44 UTC by Grefleon

2020-05-04 14:49 UTC, dante18 submitted a review, later dismissed
OK

2020-05-04 14:51 UTC, sblondeau requested changes
le controlleur doit s'appeller EventController (au singulier !)
et eventManager pour le Manager ;-)
et les vues dans un dossier Event

2020-05-04 15:23 UTC, dante18 approved these changes
OK

2020-05-05 07:19 UTC, sblondeau approved these changes

2020-05-05 07:19 UTC, merged