S04 us21 catalog admin add element
WildCodeSchool/orleans-php-2003-project-ambl pull request #96
Opened 2020-05-05 11:26 UTC by dante18

Adding the catallogAdminAdd page

2020-05-05 11:42 UTC, Grefleon requested changes

2020-05-05 11:42 UTC, Grefleon commented on public/assets/css/catalog.css
> +    background-color: #4C591E;
Faudrait mettre les couleurs en variables

2020-05-05 11:42 UTC, Grefleon commented on public/assets/css/catalogAdmin.css
> +    color: #2ea591;
Pareil ici

2020-05-05 11:42 UTC, Grefleon commented on src/View/CatalogAdmin/_form.html.twig
> +<form novalidate method="post" enctype="multipart/form-data">
T'as oublié le novalidate

2020-05-05 13:50 UTC, Grefleon submitted a review, later dismissed
Ok

2020-05-05 14:27 UTC, sblondeau requested changes

2020-05-05 14:27 UTC, sblondeau commented on public/assets/css/catalogAdmin.css
> +    -webkit-transition: outline-offset .15s ease-in-out, background-color .15s linear;
le -webkit-transition est inutile
transition tout seul est suffisant car supporté dans tous les navigateurs depuis une dizaine d'années ;-)

2020-05-05 14:27 UTC, sblondeau commented on public/assets/css/catalogAdmin.css
> +.files input:focus{     outline: 2px dashed #92b0b3;  outline-offset: -10px;
attention à l'indentation
fais bien des retours à la ligne après chaque accolade de CSS

2020-05-05 14:27 UTC, sblondeau commented on public/assets/css/catalogAdmin.css
> +    text-align: center !important;
pas de !important

2020-05-05 14:27 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +                if (file_exists($filePath)) {
si tu veux vérifier que l'upload est ok, fait directement if(move_upload_file(...))  et enlève le la ligne au dessus
move_upload_file renvoie un booleen en fonction de son succès ou non

2020-05-05 14:27 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +            $errorMessage[] = 'Le nom commun doit être inférieur a ' . $commonNameLenght . ' caractères';
length pas lenght

2020-05-05 14:27 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +        if ($_FILES['picture']['error'] == 4) {
tu fais une construction un peu compliquée et confuse
tu as $fileSend en paramètre (tu lui passe $_FILES dans le controleur)
et ensuite là tu réutilise direct $_FILES['picture']
alors qu'il faudrait faire $fileSend['picture'], sinon pas d'intéret de passer le paramètre
mais si on veut aller plus loin, autant passer directe $_FILES['picture'] depuis le controleur
du coup le foreach sur $_FILES en dessous devient inutile

2020-05-05 14:27 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +            $tmpFilePath = $fileSend['picture']['tmp_name'];
tu peux te passer de cette variable et appeler direct $fileSend['tmp_name'];

2020-05-05 14:27 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +            if ($tmpFilePath != "") {
ta verif là me semble redondante avec celle que tu fais au dessus avec le code erreur à 4
en fait, contente toi de verif que le code erreur est à 0, sinon tu gères une erreur "pb de transfert"

2020-05-05 14:27 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +        $fileExtensionAllowed = ['jpg', 'png', 'gif'];
il faut gérer les types mime et non les extensions

2020-05-05 14:27 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +            $errorMessage = 'Le fichier doit être une image et sa taille doit être inférieure à 1 MO';
je comprend pas tes 3 if/elseif
il te faut juste un if avec un in_array pour les mime types 
et un if pour la size. Et réutilise de $fileSizeMax/1000000 dans ton message d'erreur

2020-05-06 09:18 UTC, sblondeau requested changes

2020-05-06 09:18 UTC, sblondeau commented on public/assets/css/catalogAdmin.css
> +    outline: 2px dashed #92b0b3;
couleur en variable

2020-05-06 09:18 UTC, sblondeau commented on public/assets/css/catalogAdmin.css
> +    outline: 2px dashed #92b0b3;  outline-offset: -10px;
couleur variable (je te laisse modifier un peu partout ou c'est nécessaire)

2020-05-06 09:18 UTC, sblondeau commented on public/assets/css/catalogAdmin.css
> +    background-image: url(https://image.flaticon.com/icons/png/128/109/109612.png);
pas sur que ce soit le meilleur moyen de mettre une icone... 
tu as des librairies qui sont vraiment fait pour
au choix sur bootstrap, fontawesome, etc.
meme sur flaticon, tu peux dowload l'image, ou mieux utiliser le SVG)

2020-05-06 09:18 UTC, sblondeau commented on public/assets/css/catalogAdmin.css
> +    background-color:#f1f1f1;
couleur

2020-05-06 09:18 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +                if ($dataSend['type'] == '1') {
non pas '1' en dur, récupère plutot la chaine "mushroom" ou "plant" et pas un id, car tu n'es jamais sur que l'id sera tjs 1 ou 2

2020-05-06 09:18 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +                        $fileName = 'mushroom_image.jpeg';
en fait plutot que d'enregistrer en BDD la chaine correspondant à l'image par défaut, tu ferais mieux de laisser vide, et uniquement dans la vue, si l'image est vide en BDD, tu affiches l'image "placeholder" qui va bien

2020-05-06 09:18 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +        $commonNameLenght = 255;
length pas lenght, à modif partout

2020-05-06 09:18 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +                    $errors[] = 'Le type est inconnue';
est inconnu

2020-05-06 09:18 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +                $errors[] = 'Le toxicity doit être renseigné';
La toxicité doit être renseignée

2020-05-06 09:18 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +                    $errors[] = 'Le toxicity est inconnue';
La toxicité

2020-05-06 09:18 UTC, sblondeau commented on src/Services/UploadeManager.php
> +class UploadeManager
UploadManager

2020-05-06 15:21 UTC, sblondeau requested changes

2020-05-06 15:21 UTC, sblondeau commented on src/View/CatalogAdmin/index.html.twig
> +                                    {% endif %}
plutot
```
<div class="status">
{% if element.toxicity_name == 'none'  %}
      <p>{{ element.toxicity_name }}</p>
{% endif %}
</div>
```

2020-05-06 15:21 UTC, sblondeau commented on src/View/CatalogAdmin/index.html.twig
> +                                    <img src="/assets/images/catalog/{{ element.picture }}" alt="">
c'est plutot ici que je gèrerais l'image par défaut
si {{element.picture}} est empty, j'affiche "{{element.type}}.png" et tu aurais une image champignon.png et une plante.png

2020-05-06 15:21 UTC, sblondeau commented on src/Controller/CatalogAdminController.php
> +                $fileName = 'botanic.jpg';
je gèrererais plutot ça dans la vue, et je l'aisserais vide en BDD si pas d'image, voir commentaire dnas le fichier de la vue

2020-05-06 15:21 UTC, sblondeau commented on src/View/CatalogAdmin/_form.html.twig
> +        <input type="text" name="latinName" class="form-control" placeholder="ex:tremella" value="{{ dataSend.latinName }}" required>
ton placeholder est l'exemple, pas besoin de rajouter le "ex:" devant chaque valeurs de placeholder

2020-05-07 14:00 UTC, Grefleon approved these changes
Ok

2020-05-09 07:40 UTC, sblondeau approved these changes

2020-05-09 07:40 UTC, merged